name: dilute-right # Will be used for network auto naming and image names
services:
  app:
    image: 'juronja/dilute-right:latest'
    pull_policy: always
    container_name: dilute-right
    restart: unless-stopped
    ports:
      - '7474:80' # These ports are in format <host-port>:<container-port>
