name: Docker Image CI

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build . -t juronja/dilute-right:latest
    - name: Push docker image to Docker hub
      run: docker login -u juronja -p ${{ secrets.DOCKER_HUB_TOKEN }} && docker push juronja/dilute-right:latest

